sudo: required
services:
- docker
dist: trusty
env:
  global:
  - PKG_NEXUS_HOST=https://repo.cloud.ba.infn.it
  - PKG_UPLOAD_RPMS=1
  - secure: oLPTxviPeC6Y/jRM4gdZsKFSBAVzU4jtF8Ycsp7M3p1TjywL8l3y9xv7+pzeuu2I6c4+tVxNSpJ6NLn02JoueyUQFCXj8Qosl7wMi6U/Q35EcdP1veApKeJQtNGT5c8o8NL1jES+NTzNSFGoRL8l8E9G85QSxtjI19xASXgmlO8EGGO7pmdquIayT2hx7hOUnNU1nfS/4AULxkJPtzgzcDfmK3vsqB20yEMOMCuYoQQd17tzX6H0AdR9YHMV/+JJ24BcZq3JUYAocGlFIihkm6MHJZaZ32ojJd6WC6RdhbBeTot8Jm/8ozSYZEx87n90Rg58mwgAeguteybWuZo0hlKI/RmQPKgIMXTaZ/eAWjAycQTRrrkJc3OW+PbNkmSpsSWvQdoDaNwZs7mgnBJXm/PP+66KaS2oAXylDfh1aa3bO4JucvB0HxHVxqMUKghz5Ut0vbqIh9Rf7vj/qfCtVlkYKLXQb2SnubeGbbMxRMXJVJrRk1s2yqYwV/QvjWU+AYvRfcKK+Bk/oBajNkclZrc+dQdW5BJntApgeUU58YmkRhGlPG73vQZZ9FtZ82O4MkHzSOim+Vg/+RrgqWduc06tHjQwzfMkJKYpYpXQb2Fcl3DssbPNCW7bMi+uOE+5wvOXYamPk3UbMIwpsH+1mEZmbMdD6MPN0aPtDSOqm4c=
  - secure: Z702brM5DiOFljQrsPLSu9lMem0aHnRsNc/01MHobC3AvccWZkdLUiYAJYSTBOc/ad1eGKcaq08py292iIhF5Ov0W/2Oti42NX8EvLi6F1QYSlWn9PnwPvnBeaZcV4TkQ1cso9cWnNaMtYQp50AmAQ9MS4ogTUxIy+1clYehX42g0o1e0fQgHpme8AO6HvIMewEFOXeqNVlFTCkV8ZCjiniMMA5nQOS595GSR45DuoMdOKGjD3XiEtjGspIS2+oExDwZmhPi33bW0gGPy+kWG5iZoME4P/olPF5X17h8bfx/f1DqiigWcfSYqcavkBhRMklqPgztjnDBFLtzdxHBRAaFmZ7iZI9lHjFRDPR7GHbHYLq4MlIziEp2sGwEimLvgTAJbz/TNL4WpW8Ozd3g1APHDdTXG2VO/kMAjxeMInnwNwXaLTv52b4zUxnlVdXolp7TMZWK/MwswJaxdKTAYWewvoUMHid4EkN6b/HguhMkafgUV03mlrsHKK3zIaPK1e508yFh1u6Ch/bAAXjAsY/HT2ka99COzOuvrck4tKYg0vAV7gUlgLo+AGyFHZumkfSymCmGVR2zcg3MqH7pR8Qn55A2vbSCb47mMrldp1loahHQUnvIaFQuN2fliW+6zh5IfqxPlgM2hNb6IxZm8Rj1YH7v4uckq0nmeClnn2A=
script:
- bash travis/deploy.sh
